version: '3.8'

services:
  api:
    build: .
    container_name: ragbot_api_3
    ports:
      - "8686:8687"
    volumes:
      - ./ragbot/VectorDB:/app/ragbot/VectorDB
      - ./ragbot/cache_db:/app/ragbot/cache_db
      - ./ragbot/rag-configs.yaml:/app/ragbot/rag-configs.yaml
      - ./saved_models:/app/saved_models
      - log_data:/var/log  # Shared volume for log files
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - LLM_MODEL=gemma2:9b-instruct-fp16

    restart: always
    depends_on:
      - ollama
      - kibana
      - elasticsearch
    networks:
      - ollama-docker2

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia

  ollama:
    image: ollama/ollama:latest
    ports:
      - 8089:11434
    volumes:
      - /usr/share/ollama/.ollama/:/root/.ollama
    container_name: ollama
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_NUM_PARALLEL=4
      # - CUDA_VISIBLE_DEVICES=0
    networks:
      - ollama-docker2

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MySecretPassword123!@#
      POSTGRES_DB: chatbot
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - ollama-docker2
    restart: always
    user: root
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "8688:80"
    tty: true
    networks:
      - ollama-docker2
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: admin
    user: root
    restart: always
    volumes:
      - ./pgadmin:/var/lib/pgadmin

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      # - ./esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - ollama-docker2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=RASFyGVFAtgtk+2N/PL/rsWvrykiHOtufLiN0+2HyXc=
    ports:
      - 8001:5601
    networks:
      - ollama-docker2

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.9
    container_name: filebeat
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - log_data:/var/log  # Mount the same shared volume here
    networks:
      - ollama-docker2
    depends_on:
      - elasticsearch
    user: root
    command: >
      sh -c "chown root:root /usr/share/filebeat/filebeat.yml &&
            chmod go-w /usr/share/filebeat/filebeat.yml &&
            filebeat -e -c /usr/share/filebeat/filebeat.yml"

volumes:
  log_data:  
  VectorDB:
  postgres_data:
  redis_data:
  esdata:

networks:
  ollama-docker2:
    external: false
    driver: bridge
  # logstash:
  #   image: docker.elastic.co/logstash/logstash:7.17.9
  #   container_name: logstash
  #   # volumes:
  #   #   - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  #   ports:
  #     - "5044:5044" # Filebeat to Logstash
  #     - "9600:9600" # Logstash monitoring
  #   environment:
  #     - "xpack.monitoring.enabled=false"
  #   networks:
  #     - ollama-docker2

  # redis-stack:
  #   image: redis/redis-stack:latest
  #   container_name: redis-stack
  #   ports:
  #     - "6379:6379" # Redis server
  #     - "8001:8001" # Redis Insight UI
  #   environment:
  #     REDIS_ARGS: >
  #       --appendonly yes
  #   volumes:
  #     - redis_data:/data
  #     # - ./redis.conf:/etc/redis/redis-stack.conf # Mount redis.conf file
  #     # - ./redis.conf:/redis-stack.conf
  #   # command: ["redis-stack-server", "/etc/redis/redis.conf"]
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3

  #   networks:
  #     - ollama-docker2
  #   restart: always
