version: '3.8'

services:
  api:
    build: .
    container_name: ragbot_api
    ports:
      - "8687:8687"
    volumes:
      - ./ragbot/VectorDB:/app/ragbot/VectorDB
      - ./ragbot/rag-configs.yaml:/app/ragbot/rag-configs.yaml
      - ./saved_models:/app/saved_models
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - LLM_MODEL=gemma2:9b-instruct-fp16
      
    command: uvicorn api:app --host 0.0.0.0 --port 8687 --reload
    restart: always
    depends_on:
      - ollama
    networks:
      - ollama-docker

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia

  ollama:
    image: ollama/ollama:latest
    ports:
      - 8089:11434
    volumes:
      - /usr/share/ollama/.ollama/:/root/.ollama
    container_name: ollama
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    networks:
      - ollama-docker

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia


  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MySecretPassword123!@#
      POSTGRES_DB: chatbot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ollama-docker
    restart: always
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "8080:80"
    tty: true
    networks:
      - ollama-docker
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
    volumes:
      - ./pgadmindаta:/var/lib/pgadmin

volumes:
  VectorDB:
  postgres_data:

networks:
  ollama-docker:
    external: false
