filebeat.inputs:
- type: filestream
  id: my-filestream-id
  enabled: true
  paths:
    - /var/log/HamBot.log  # Only include this specific log file
  exclude_files:
    - '/var/log/dpkg.log$'          # Exclude dpkg.log
    - '/var/log/alternatives.log$'  # Exclude alternatives.log
    - '/var/log/.*\.log'            # Optionally exclude all other .log files except specified ones

  # Parse JSON logs
  json.keys_under_root: true
  json.add_error_key: true

# Disable default modules
filebeat.config.modules:
  enabled: false

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:8001"

processors:
  - drop_fields:
      fields: ["host", "agent", "data_stream", "event", "tags"]
