filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/HamBot.log  # Only include this specific log file
  exclude_files:
    - '/var/log/dpkg.log$'          # Exclude dpkg.log
    - '/var/log/alternatives.log$'  # Exclude alternatives.log
    - '/var/log/.*\.log'            # Optionally exclude all other .log files except specified ones

  json.keys_under_root: true  # Moves JSON keys to the top-level
  json.add_error_key: true    # Adds error key for malformed JSON logs
  json.message_key: ""        # Disable mapping to 'message' field, so it’s not created


# Disable default modules
filebeat.config.modules:
  enabled: false

output.elasticsearch:
  hosts: ["localhost:9200"]
  pipeline: "json_parser_pipeline"

setup.kibana:
  host: "http://kibana:8001"

# processors:
#   - drop_fields:
#       fields: ["host", "agent", "data_stream", "event", "tags"]
