input {
  beats {
    port => 5044
  }
}

filter {
  json {
    source => "message"
    target => "parsed_json"
  }

  ruby {
    code => "
      event.get('parsed_json').each do |k, v|
        event.set(k, v)
      end
      event.remove('parsed_json')
      event.remove('message')
    "
  }

  date {
    match => [ "logtime", "yyyy-MM-dd HH:mm:ss.SSS" ]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "logstash-%{+YYYY.MM.dd}"
  }
}
