# Redis configuration file
# include /etc/redis/redis-stack.conf
# Network settings
bind 0.0.0.0
port 6379
# requirepass myRedisPassword123

# Persistence settings
save 900 1
save 300 10
save 60 10000
appendonly yes
appendfilename "appendonly.aof"
dir /data


# Load Redis Stack modules with correct paths
# loadmodule /opt/redis-stack/lib/redisearch.so
# Add other modules if needed
# loadmodule /opt/redis-stack/lib/redistimeseries.so
# loadmodule /opt/redis-stack/lib/redisgraph.so
# loadmodule /opt/redis-stack/lib/redisbloom.so
# loadmodule /opt/redis-stack/lib/redisai.so
# loadmodule /opt/redis-stack/lib/redisgears.so
# loadmodule /opt/redis-stack/lib/redistdigest.so

# Enable Redis Insight
# redis-stack-server yes
