# Configurations for vector database
database:
  persist_directory:  VectorDB
  dbname: my-vdb
  documents_addr: /home/user01/mj-workspace/Assistant-bot/RagBot/new-KB/FAQ-202411408-temp.docx

# Configurations for logging
logging:
  level: debug
  file: app.log
  max_size: 10*1024*1024

api:
  port: 8686

# Configurations for streamlit
streamlit:
  host: 0.0.0.0
  port: 8505

# configurations for ollama
ollama:
  # model_name: qwen2:72b-instruct-q4_K_M
  model_name: gemma2:9b-instruct-fp16
  temperature: 0
  stream: true
  keep_alive: 120
  saved_models: /apt/saved_models/qwen/


# configurations for embedding model
embedding_model:
  #model_name: BAAI/bge-m3
  model_name: ../saved_models/models--BAAI--bge-m3/snapshots/babcf60cae0a1f438d7ade582983d4ba462303c2
  device: cuda

# configurations for reranker
reranker:
  #model_name: BAAI/bge-reranker-v2-m3
  model_name: ../saved_models/models--BAAI--bge-reranker-v2-m3/snapshots/12e974610ba9083ed95f3edf08d7e899581f4de4
  device: cpu
  cutoff: 10

# configurations for retriever
retriever:
  retrieved_documents: 10 # initiate_vdb.py
  retrieved_rank2_documents: 5
  alpha_threshold: 0
  expansion: false
  rerank: true
  chunk_size: 1000
  max_chunk_size: 1200
  sentence_overlap: 1
  history_length: 2


# configurations for langchain
langchain:
  enabled: true
  model_path: ./models/langchain_model.pth
  model_type: LangChain
  model_name: en-de

# Evaluations configurations
evaluation:
  persist_directory: ./VectorDB-Eval
  dbname: my-vdb
  documents_addr: /home/user01/mj-workspace/Assistant-bot/RagBot/new-KB/FAQ-202411408-temp.docx
  dataset: /home/user01/mj-workspace/Assistant-bot/RagBot/evaluation/Copy-of-QA-sep.csv
  # model_name: qwen2:72b-instruct-q6_K  
  model_name: gemma2:9b-instruct-fp16 
  output_path: /home/user01/mj-workspace/Assistant-bot/RagBot/evaluation/
  retrieved_documents: 10
  retrieved_rank2_documents: 5
  # chunk_size: 300
  # chunk_overlap: 50

chat_responder:
  ok_status: "OK"
  doubtful_status: "DOUBTFUL"
  no_answer_status: "NO_ANSWER"
  error_status: "error"
