# Configurations for vector database
database:
  persist_directory:  VectorDB
  dbname: my-vdb
  documents_addr: KB-tavalla

# Configurations for logging
logging:
  level: debug
  file: app.log
  max_size: 10*1024*1024

api:
  port: 8687

# Configurations for streamlit
streamlit:
  host: 0.0.0.0
  port: 8505

# configurations for ollama
ollama:
  model_name: gemma2:9b-instruct-fp16 # llama3.1:70b-instruct-q3_K_S  
  temperature: 0
  stream: true
  keep_alive: 120
  saved_models: /apt/saved_models/qwen/


# configurations for embedding model
embedding_model:
  #model_name: BAAI/bge-m3
  model_name: ../saved_models/models--BAAI--bge-m3/snapshots/babcf60cae0a1f438d7ade582983d4ba462303c2
  device: cuda

# configurations for reranker
reranker:
  #model_name: BAAI/bge-reranker-v2-m3
  model_name: ../saved_models/models--BAAI--bge-reranker-v2-m3/snapshots/12e974610ba9083ed95f3edf08d7e899581f4de4
  device: cuda
  cutoff: 10

# configurations for retriever
retriever:
  retrieved_documents: 5
  alpha_threshold: 0.1
  max_context_length: 4
  expansion: false
  rerank: true
  chunk_size: 750
  max_chunk_size: 1200
  chunk_overlap: 50
  sentence_overlap: 1
# 1000, 1200, 3

# configurations for langchain
langchain:
  enabled: true
  model_path: ./models/langchain_model.pth
  model_type: LangChain
  model_name: en-de

# Evaluations configurations
evaluation:
  persist_directory: ./VectorDB-Eval
  dbname: my-vdb
  documents_addr: /app/ragbot/assets/FAQ-202411408-temp.docx
  # documents_addr: /app/ragbot/assets/
  # dataset: /app/ragbot/evaluation/IN_QAQUESTIONS_TEMP.csv
  dataset: /app/ragbot/evaluation/copy-of-QA-sep.csv
  model_name: gemma2:9b-instruct-fp16
  output_path: /app/ragbot/evaluation/
  retrieved_documents: 10
  retrieved_rank2_documents: 5
  chunk_size: 500
  chunk_overlap: 50

chat_responder:
  ok_status: "OK"
  doubtful_status: "DOUBTFUL"
  no_answer_status: "NO_ANSWER"
  error_status: "error"
                          