# Configurations for vector database
database:
  response_type: concise
  persist_directory: ../VectorDB # initiate_vdb.py # ./VectorDB-bahar-hanieh #./VectorDB
  does_evaluate: False
  company_name: "همکاران سیستم"
  assistant_name: "digital assistant"
  use_cache: True
  dbname: my-vdb
  collection_name: "default_collection"
  documents:
    4thg-intro: معرفی سیستم یکپارچه نسل 4
    crm: مدیریت ارتباط با مشتری
    da: راهنمای استفاده از دستیار دیجیتال
    gl: دفتر کل
    hcm: جبران خدمات
    inv: انبار
    platform: امکانات عمومی کاربر
    reportbuilder: گزارش ساز
    sales: فروش
    taxpayer: مودیان مالیاتی
    treasury: خزانه داری

# Configurations for logging
logging:
  level: debug
  file: app.log
  max_size: 10*1024*1024


api:
  port: 8686


modules:
  names: 
    sales: فروش
    hcm: جبران خدمات
    da: دستیار دیجیتال
    taxpayer: مودیان
    treasury: خزانه داری
    gl: دفتر کل
    reportbuilder: گزارش ساز
    inv: انبار
    4thg-intro: مقدمه
    help: راهنما
    crm: مدیریت ارتباط با مشتری
    aboutsg: درباره همکاران سیستم
    platform: پلتفرم
  
  proposable_modules:
    - انبار
    - جبران خدمات
    - خزانه داری
    - دفتر کل
    - فروش
    - مدیریت ارتباط با مشتری
    - مودیان مالیاتی
    - گزارش ساز

postgres:
  address: 172.26.0.6 # 172.26.0.5 # postgres # 172.26.0.6 # postgres # 172.20.0.6 # 192.168.208.2
  database: chatbot
  max_user_input_character_length: 200
  history_length: 3


cache:
  # host: redis-stack
  host: 127.0.0.1
  port: 9200
  knn: 1
  alpha_threshold: 0.1
  beta_threshold: 0.2
  redis_result_num_documents: 5
  socket_timeout: 10
  index_name: Hamzan
  persist_directory: ../db-cache
  index_name: default_cache
  num_rank2_documents: 5
  embedding_model:
#    model_name: /home/jovyan/.cache/huggingface/hub/models--intfloat--multilingual-e5-large/snapshots/0dc5580a448e4284468b8909bae50fa925907bc5
    model_name: ../saved_models/models--intfloat--multilingual-e5-large/snapshots/0dc5580a448e4284468b8909bae50fa925907bc5
    device: cuda

  # configurations for reranker
  reranker:
    model_name: # ../saved_models/models--BAAI--bge-reranker-v2-m3/snapshots/12e974610ba9083ed95f3edf08d7e899581f4de4
    # model_name: /home/user01/.cache/huggingface/hub/models--BAAI--bge-reranker-v2-gemma/snapshots/1787044f8b6fb740a9de4557c3a12377f84d9e17
#    model_name: BAAI/bge-reranker-v2-m3
    device: cpu
    cutoff: 10
    
  schema:
    query_field_name: query
    vector_field_name: vector
    answer_field_name: answer
    url_field_name: url
    message_id_field_name: message_id
    thumb_up_field_name: thumb_up
    thumb_down_field_name: thumb_down
    flag_field_name: flag


# Configurations for streamlit
streamlit:
  host: 0.0.0.0
  port: 8505


# configurations for embedding model
embedding_model:
  model_path: ../saved_models/models--intfloat--multilingual-e5-large/snapshots/0dc5580a448e4284468b8909bae50fa925907bc5
  device: cuda
  # Type: "triton" or "local"
  # type: triton
  # Triton Embedding Configuration
  model_name: "qwen3-embedding-4b"  # Model name in Triton server
  triton_url: http://triton-server.admin.svc.cluster.local
  tokenizer_path: ../saved_models/models--intfloat--multilingual-e5-large/snapshots/0dc5580a448e4284468b8909bae50fa925907bc5
  max_length: 8192
  timeout: 30
  batch_size: 32
  type: "openrouter"

# configurations for reranker
reranker:
  # primary_model: flag
  # type: triton
  type: service
  # model_name: bge  # Same model serving both embedding and reranking
  model_name: Qwen3-Reranker-4B
  triton_url: http://triton-server.admin.svc.cluster.local
  max_length: 8192
  api_type: custom_v2 # legacy OR openrouter
  api_url: http://qwen3-rr-4b-predictor.admin.svc.cluster.local/v2/rerank 
  batch_size: 32
  flag_model: 
      model_path: ../saved_models/models--BAAI--bge-reranker-v2-m3
      device: cuda
  
  qwen_model: 
      model_path: ../saved_models/qwen3-reranker
      device: cuda
      max_length: 8192


# configurations for retriever
retriever:
  retrieved_documents: 40
  retrieved_rank2_documents: 7
  retriever_threshold: 0.0
  alpha_threshold: 0.5
  use_reranker: False
  

# Evaluations configurations
evaluation:
  persist_directory: ./VectorDB-Eval-2
  dbname: my-vdb
  documents:
    /home/user01/mj-workspace/Assistant-bot/RagBot/new-KB/GL_QA_Base Data-temp.docx:
      target_chunk_size: 800
      max_chunk_size: 1200
      sentence_overlap: 1

  dataset: /home/user01/mj-workspace/Assistant-bot/RagBot/eval-questions/GL_QA_Questions.csv
  model_name: qwen2.5:32b-instruct-q5_K_M
  output_path: /home/user01/mj-workspace/Assistant-bot/RagBot/evaluation/
  retrieved_documents: 12
  retrieved_rank2_documents: 5


chat_responder:
  ok_status: "success"
  doubtful_status: "DOUBTFUL"
  no_answer_status: "NO_ANSWER"
  error_status: "error"


followup_query_generator:
  number_of_suggested_queries: 3

router_model:
  address: ../saved_models/svm.joblib
  openrouter: "qwen/qwen3-embedding-4b"
  embedding_model: "qwen3-embedding-4b"
  model_name: svm
  beta_threshold: 0.3
  alpha_threshold: 0.7