# Configurations for vector database
database:
  persist_directory: ../VectorDB # initiate_vdb.py # ./VectorDB-bahar-hanieh #./VectorDB
  dbname: my-vdb
  documents:
    ../../knowledge_base/new-KB/UPDATED-FAQ 202411408-temp.docx:
      target_chunk_size: 800
      max_chunk_size: 1200
      sentence_overlap: 1
    ../../knowledge_base/new-KB/GL_CompleteDoc-new-temp.docx:
      target_chunk_size: 700
      max_chunk_size: 1200
      sentence_overlap: 1
    ../../knowledge_base/new-KB/AboutSG-temp.docx:
      target_chunk_size: 800
      max_chunk_size: 1200
      sentence_overlap: 1
    ../../knowledge_base/new-KB/DA-Help-temp.docx:
      target_chunk_size: 800
      max_chunk_size: 1200
      sentence_overlap: 1

# Configurations for logging
logging:
  level: debug
  file: app.log
  max_size: 10*1024*1024

api:
  port: 8686

postgres:
  address: postgres # 192.168.16.6 
  database: chatbot
  max_user_input_character_length: 200
  history_length: 3

cache:
  # host: redis-stack
  host: 127.0.0.1
  port: 9200
  knn: 50
  alpha_threshold: 0.1
  beta_threshold: 0.2
  redis_result_num_documents: 5
  socket_timeout: 10
  index_name: Hamzan
  persist_directory: ../db-cache
  num_rank2_documents: 5
  embedding_model:
    #model_name: BAAI/bge-m3
    model_name: ../saved_models/models--BAAI--bge-m3/snapshots/babcf60cae0a1f438d7ade582983d4ba462303c2
    device: cuda

  # configurations for reranker
  reranker:
    # model_name: BAAI/bge-reranker-v2-m3
    # model_name: /home/user01/.cache/huggingface/hub/models--BAAI--bge-reranker-v2-gemma/snapshots/1787044f8b6fb740a9de4557c3a12377f84d9e17
    device: cuda
    cutoff: 10
    
  schema:
    query_field_name: query
    vector_field_name: vector
    answer_field_name: answer
    url_field_name: url
    message_id_field_name: message_id
    thumb_up_field_name: thumb_up
    thumb_down_field_name: thumb_down
    flag_field_name: flag

# Configurations for streamlit
streamlit:
  host: 0.0.0.0
  port: 8505

# configurations for ollama
ollama:
  # model_name: qwen2:72b-instruct-q4_K_M
  # model_name: gemma2:9b-instruct-fp16
  model_name: aya-expanse:32b-q5_K_M
  # model_name: gemma2:27b-instruct-q8_0
  temperature: 0
  stream: true
  keep_alive: -1
  saved_models: /apt/saved_models/qwen/


# configurations for embedding model
embedding_model:
  #model_name: BAAI/bge-m3
  model_name: ../saved_models/models--BAAI--bge-m3/snapshots/babcf60cae0a1f438d7ade582983d4ba462303c2
  # model_name: /home/user01/.cache/huggingface/hub/models--alefbot--alef-zibert/snapshots/b5a9d43b612b57191bb3a618b51b09b8ecabd927
  device: cpu

# configurations for reranker
reranker:
  #model_name: BAAI/bge-reranker-v2-m3
  model_name: ../saved_models/models--BAAI--bge-reranker-v2-m3/snapshots/12e974610ba9083ed95f3edf08d7e899581f4de4
  # model_name: /home/user01/.cache/huggingface/hub/models--BAAI--bge-reranker-v2-gemma/snapshots/1787044f8b6fb740a9de4557c3a12377f84d9e17
  device: cpu

# configurations for retriever
retriever:
  retrieved_documents: 12 # initiate_vdb.py
  retrieved_rank2_documents: 6
  alpha_threshold: 0
  expansion: false
  rerank: true
  chunk_size: 800
  max_chunk_size: 1200
  sentence_overlap: 1
  retriever_threshold: 0.002

# configurations for langchain
langchain:
  enabled: true
  model_path: ./models/langchain_model.pth
  model_type: LangChain
  model_name: en-de

# Evaluations configurations
evaluation:
  persist_directory: ./VectorDB-Eval-2
  dbname: my-vdb
  documents:
    # /home/user01/mj-workspace/Assistant-bot/RagBot/new-KB/UPDATED-FAQ 202411408-temp.docx:
    #   target_chunk_size: 750
    #   max_chunk_size: 1200
    #   sentence_overlap: 1
    /home/user01/mj-workspace/Assistant-bot/RagBot/new-KB/GL_QA_Base Data-temp.docx:
      target_chunk_size: 800
      max_chunk_size: 1200
      sentence_overlap: 1

  # dataset: /home/user01/mj-workspace/Assistant-bot/RagBot/eval-questions/Copy-of-QA-sep.csv
  dataset: /home/user01/mj-workspace/Assistant-bot/RagBot/eval-questions/GL_QA_Questions.csv
  # model_name: gemma2:9b-instruct-fp16 
  model_name: qwen2.5:32b-instruct-q5_K_M
  # model_name: gemma2:27b-instruct-q8_0 
  output_path: /home/user01/mj-workspace/Assistant-bot/RagBot/evaluation/
  retrieved_documents: 12
  retrieved_rank2_documents: 5
  # chunk_overlap: 50

chat_responder:
  ok_status: "success"
  doubtful_status: "DOUBTFUL"
  no_answer_status: "NO_ANSWER"
  error_status: "error"


followup_query_generator:
  number_of_suggested_queries: 3


  # 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
