input {
  file {
    path => "/var/log/HamBot.log"
    start_position => "beginning"
    codec => "json"
  }
}

filter {
  # Drop specific fields
  mutate {
    remove_field => [
      "host", 
      "data_stream", 
      "event", 
      "tags"
    ]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logstash-%{+YYYY.MM.dd}"
      }
}